/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-03-20 07:21:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class challenge_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/E:/semiproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/eojintemplate/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1489992988000L));
    _jspx_dependants.put("/footer.jspf", Long.valueOf(1489980826000L));
    _jspx_dependants.put("jar:file:/E:/semiproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/eojintemplate/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/header.jspf", Long.valueOf(1489992616000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<!--[if lt IE 7]> <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>    <html class=\"no-js lt-ie9 lt-ie8\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>    <html class=\"no-js lt-ie9\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("<head>\r\n");
      out.write("<title>Vintage | Challenge</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/superfish.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/nivo-slider.css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/tweet.css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/lessframework.css\" media=\"all\">\r\n");
      out.write("<script src=\"js/modernizr-2.5.3.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table {\r\n");
      out.write("border-spacing: 9px;\r\n");
      out.write("}\r\n");
      out.write("table td {\r\n");
      out.write("width: 70px;\r\n");
      out.write("background: #ccc;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- HEADER -->\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      out.write("  <!-- header wrapper -->\r\n");
      out.write("  <div></div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"wrapper cf\">\r\n");
      out.write("    <div id=\"logo\"> <a href=\"index.jsp\" ><img src=\"img/kostalogo.png\" alt=\"\"></a> </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- ENDS header wrapper -->\r\n");
      out.write("  <!-- nav -->\r\n");
      out.write("  <nav class=\"cf\">\r\n");
      out.write("    <div class=\"wrapper cf\">\r\n");
      out.write("      <ul id=\"nav\" class=\"sf-menu\">\r\n");
      out.write("        <li><a href=\"index.jsp\">HOME<i><b></b></i></a></li>\r\n");
      out.write("        <li><a href=\"best.jsp\">Best<i><b></b></i></a>\r\n");
      out.write("<!--           <ul>\r\n");
      out.write("            <li><a href=\"page.jsp\">Columns</a></li>\r\n");
      out.write("            <li><a href=\"page-typography.jsp\">Typography</a></li>\r\n");
      out.write("            <li><a href=\"page-elements.jsp\">Elements</a></li>\r\n");
      out.write("          </ul> -->\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a href=\"bestChallenge.jsp\">Best Challenge<i><b></b></i></a></li>\r\n");
      out.write("        <li><a href=\"challenge.jsp\">Challenge<i><b></b></i></a></li>\r\n");
      out.write("        <!-- ë¡ê·¸ì¸ ìëì´ììëë  <li><a href=\"login.jsp\">member<i><b></b></i></a></li> <li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("            <li><a href=\"join.jsp\">Join</a></li>\r\n");
      out.write("            \r\n");
      out.write("\t\t            ë¡ê·¸ì¸ ëì´ììë íìì´ë©´ íìì ë³´ / ê´ë¦¬ìë©´ ê´ë¦¬ìê´ë¦¬ê° íìëê² í´ì£¼ë©´ ì¢ìë¯\r\n");
      out.write("            -->\r\n");
      out.write("\t\t        <li><a href=\"login.jsp\">member<i><b></b></i></a>\r\n");
      out.write("   \t    \t\t\t<ul>\r\n");
      out.write("       \t \t\t\t\t<li><a href=\"login.jsp\">login</a></li>\r\n");
      out.write("        \t\t\t   \t<li><a href=\"join.jsp\">Join</a></li>\r\n");
      out.write("       \t\t\t \t</ul>\r\n");
      out.write("        \t\t</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <div id=\"combo-holder\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- ends nav -->");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- ENDS HEADER -->\r\n");
      out.write("\t<!-- MAIN -->\r\n");
      out.write("\t<div role=\"main\" id=\"main\">\r\n");
      out.write("\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t<!-- page-content -->\r\n");
      out.write("\t\t\t<div class=\"page-content\">\r\n");
      out.write("\t\t\t\t<!-- entry-content -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<h1>Music Chart</h1>\r\n");
      out.write("\t\t\t\t\t<div align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"list.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"곡명을 입력하세요.\" name=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"btn btn-xs btn-default\" type=\"submit\" value=\"검색\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<table border=\"0\" summary=\"트랙 리스트\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"39\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"44\">\r\n");
      out.write("\t\t\t\t\t\t\t<col>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"23%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"37\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"81\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"37\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"69\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"ranking\"><span>순위</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\" _title_header title NPI=a:strack\"><span>곡명</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\" _artist_header artist NPI=a:sartist\"><span>아티스트</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"like\"><span>좋아요</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"buy\"><span>구매</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"_tracklist_move {TRACK_TYPE}\" style=\"display: none;\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttrackdata=\"{TRACK_DATA}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"name\">{PLAY_TOGGLE} {ADD_TOGGLE} <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_ico_title ico_title\"{TITLE_ICO_STYLE}><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\theight=\"18\" width=\"23\" alt=\"TITLE\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"http://static.naver.net/nmusic/201008/blank.gif\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_ico_19 ico19\"{19_ICO_STYLE}><img height=\"18\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"13\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"http://static.naver.net/nmusic/201008/blank.gif\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{TRACK_SONG_NAME}\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"_artist artist {NO_ELL}\">{ARTIST}</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"like\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"u_likeit_list_module\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" title=\"좋아요\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"u_likeit_list_btn u_type_img NPI=a:favo,r:1,i:\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-sid=\"MUSIC\" data-did=\"MUSIC\" data-cid=\"TRACK_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-likeit=\"0\"><span class=\"u_ico\"></span><em\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"u_txt\"></em><em class=\"u_cnt\"></em></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"radio\">{RADIO}</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"buy\">{MP3_BUY_LAYER_BTN}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"display: none;\" class=\"_buy_layer buy_layer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>{MP3_BUY_LIST}</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>{MUSIC_SPRING}</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>{BELL_SOUND}</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>{CONNECTION_SOUND}</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"bg\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"_tracklist_move data1  \"\r\n");
      out.write("\t\t\t\t\t\t\t\ttrackdata=\"3182429|30971|true|true|false|true|true|true|0|true|true|false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"ranking\"><span class=\"num1\"><span>1</span></span></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"name\"><a href=\"/album/index.nhn?albumId=316326\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb pht36 NPI=a:image,r:1,i:316326\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"http://musicmeta.phinf.naver.net/album/000/316/316326.jpg?type=r32Fll&v=20160829160104\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonerror=\"this.onerror=null;this.src='http://musicmeta.phinf.naver.net/album/000/000/0.jpg?type=r32Fll&v=20160829160104';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"32\" height=\"32\" alt=\"1집 버스커 버스커\" title=\"1집 버스커 버스커\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"mask\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_play_ico ico_listen NPI=a:play,r:1,i:3182429\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"http://static.naver.net/nmusic/201008/blank.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"18\" height=\"18\" alt=\"듣기\" title=\"듣기\"></a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_add_ico ico_add NPI=a:plus,r:1,i:3182429\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"http://static.naver.net/nmusic/201008/blank.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"18\" height=\"18\" alt=\"재생목록에 추가\" title=\"재생목록에 추가\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#3182429\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_title title NPI=a:track,r:1,i:3182429\" title=\"벚꽃 엔딩\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"ellipsis\">벚꽃 엔딩</span></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"_artist artist\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"/artist/home.nhn?artistId=170738\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_artist NPI=a:artist,r:1,i:170738\" title=\"버스커 버스커\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"ellipsis\"> 버스커 버스커 </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"like\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"u_likeit_list_module\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" title=\"좋아요\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"u_likeit_list_btn u_type_img NPI=a:favo,r:1,i:3182429\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-sid=\"MUSIC\" data-did=\"MUSIC\" data-cid=\"TRACK_3182429\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-likeit=\"0\"><span class=\"u_ico\"></span><em\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"u_txt\"></em><em class=\"u_cnt\"></em></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"ico\"><a href=\"#30971\" title=\"뮤직비디오\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_musicvideo video NPI=a:movie,r:1,i:30971\"><span>뮤직비디오</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"_lyric lyric NPI=a:lyric,r:1,i:3182429\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"가사\"><span>가사</span></a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_scrap get NPI=a:put,r:1,i:3182429\" title=\"내 리스트에 담기\"><span>담기</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"radio\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"window.open('http://player.music.naver.com/radio.nhn?radioType=track&seed=3182429', 'pop_alert', 'toolbar=no,scrollbars=no,width=710,height=382')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"NPI=a:radio,r:1,i:3182429\"><span>라디오</span></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"buy\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_buy NPI=a:buy,r:1,i:3182429\"><span>구매</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"display: none;\" class=\"_buy_layer buy_layer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonMouseOver=\"nhn.music.drawAirDownloadButton(this, 'list', [3182429], false);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"_buy_mp3 NPI=a:mp3,r:1,i:3182429\"><strong>MP3구매</strong></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"nhn.music.openMusicGiftPopup('track', 3182429, false);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"_gift NPI=a:gift,r:1,i:3182429\">선물하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"_music_spring NPI=a:bgm,r:1,i:3182429\">뮤직샘</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"bg\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"_tracklist_move data0  \"\r\n");
      out.write("\t\t\t\t\t\t\t\ttrackdata=\"16653915|71719|true|true|false|true|false|false|0|true|true|false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"ranking\"><span class=\"num2\"><span>2</span></span></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"name\"><a href=\"/album/index.nhn?albumId=1851868\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb pht36 NPI=a:image,r:2,i:1851868\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"http://musicmeta.phinf.naver.net/album/001/851/1851868.jpg?type=r32Fll&v=20170320150508\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonerror=\"this.onerror=null;this.src='http://musicmeta.phinf.naver.net/album/000/000/0.jpg?type=r32Fll&v=20170320150508';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"32\" height=\"32\" alt=\"CAN YOU FEEL IT?\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"CAN YOU FEEL IT?\"> <span class=\"mask\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_play_ico ico_listen NPI=a:play,r:2,i:16653915\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"http://static.naver.net/nmusic/201008/blank.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"18\" height=\"18\" alt=\"듣기\" title=\"듣기\"></a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_add_ico ico_add NPI=a:plus,r:2,i:16653915\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"http://static.naver.net/nmusic/201008/blank.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"18\" height=\"18\" alt=\"재생목록에 추가\" title=\"재생목록에 추가\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#16653915\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_title title NPI=a:track,r:2,i:16653915\" title=\"아름답다\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"ellipsis\">아름답다</span></a></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"_artist artist\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"/artist/home.nhn?artistId=1541802\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_artist NPI=a:artist,r:2,i:1541802\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"하이라이트(Highlight)\"> <span class=\"ellipsis\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t하이라이트(Highlight) </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"like\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"u_likeit_list_module\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" title=\"좋아요\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"u_likeit_list_btn u_type_img NPI=a:favo,r:2,i:16653915\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-sid=\"MUSIC\" data-did=\"MUSIC\" data-cid=\"TRACK_16653915\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-likeit=\"0\"><span class=\"u_ico\"></span><em\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"u_txt\"></em><em class=\"u_cnt\"></em></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"ico\"><a href=\"#71719\" title=\"뮤직비디오\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_musicvideo video NPI=a:movie,r:2,i:71719\"><span>뮤직비디오</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"_lyric lyric NPI=a:lyric,r:2,i:16653915\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"가사\"><span>가사</span></a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_scrap get NPI=a:put,r:2,i:16653915\" title=\"내 리스트에 담기\"><span>담기</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"radio\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"window.open('http://player.music.naver.com/radio.nhn?radioType=track&seed=16653915', 'pop_alert', 'toolbar=no,scrollbars=no,width=710,height=382')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"NPI=a:radio,r:2,i:16653915\"><span>라디오</span></a></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"buy\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"_buy NPI=a:buy,r:2,i:16653915\"><span>구매</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"display: none;\" class=\"_buy_layer buy_layer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonMouseOver=\"nhn.music.drawAirDownloadButton(this, 'list', [16653915], false);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"_buy_mp3 NPI=a:mp3,r:2,i:16653915\"><strong>MP3구매</strong></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"nhn.music.openMusicGiftPopup('track', 16653915, false);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"_gift NPI=a:gift,r:2,i:16653915\">선물하기</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"_music_spring NPI=a:bgm,r:2,i:16653915\">뮤직샘</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"bg\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- ENDS entry-content -->\r\n");
      out.write("\t\t\t\t<div class=\"c-1\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"c-2\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"c-3\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"c-4\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- ENDS page-content -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ENDS MAIN -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t");
      out.write("  <!-- wrapper -->\r\n");
      out.write("  <div class=\"wrapper cf\">\r\n");
      out.write("    <!-- social -->\r\n");
      out.write("    <div class=\"sb-holder cf\">\r\n");
      out.write("      <ul id=\"social-bar\" class=\"cf\">\r\n");
      out.write("        <li class=\"left-corner\"><i></i></li>\r\n");
      out.write("        <li><a href=\"#\" title=\"Become a fan\"><img src=\"img/social/Facebook.png\" alt=\"\"></a></li>\r\n");
      out.write("        <li><a href=\"#\" title=\"Follow my tweets\"><img src=\"img/social/Twitter.png\" alt=\"\"></a></li>\r\n");
      out.write("        <li><a href=\"#\" title=\"Add to the circle\"><img src=\"img/social/Google+.png\" alt=\"\"></a></li>\r\n");
      out.write("        <li class=\"right-corner\"><i></i></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ENDS social -->\r\n");
      out.write("    <!-- widgets -->\r\n");
      out.write("    <ul  class=\"widget-cols cf\">\r\n");
      out.write("      <li class=\"first-col\">\r\n");
      out.write("        <div class=\"widget-block\">\r\n");
      out.write("          <h4>RECENT POSTS</h4>\r\n");
      out.write("          <div class=\"recent-post cf\"> <a href=\"#\" class=\"thumb\"><img src=\"img/dummies/54x54.gif\" alt=\"\"></a>\r\n");
      out.write("            <div class=\"post-head\"> <a href=\"#\">Pellentesque habitant morbi senectus </a><span> March 12, 2011</span> </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"recent-post cf\"> <a href=\"#\" class=\"thumb\"><img src=\"img/dummies/54x54b.gif\" alt=\"\"></a>\r\n");
      out.write("            <div class=\"post-head\"> <a href=\"#\">Pellentesque habitant morbi senectus</a><span> March 12, 2011</span> </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"recent-post cf\"> <a href=\"#\" class=\"thumb\"><img src=\"img/dummies/54x54c.gif\" alt=\"\"></a>\r\n");
      out.write("            <div class=\"post-head\"> <a href=\"#\">Pellentesque habitant morbi senectus</a><span> March 12, 2011</span> </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"second-col\">\r\n");
      out.write("        <div class=\"widget-block\">\r\n");
      out.write("          <h4>ABOUT</h4>\r\n");
      out.write("          <p>Vintage Template it's completely free this means you don't have to pay anything.</p>\r\n");
      out.write("          <p>Placeholder images by twistedfork.me</p>\r\n");
      out.write("          <p>Visit our site and find the most beautiful free templates up to date.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"third-col\">\r\n");
      out.write("        <div class=\"widget-block\">\r\n");
      out.write("          <div id=\"tweets\" class=\"footer-col tweet\">\r\n");
      out.write("            <h4>TWITTER WIDGET</h4>\r\n");
      out.write("            <ul class=\"tweet_list\">\r\n");
      out.write("              <li class=\"tweet_first tweet_odd\"><span class=\"tweet_time\"><a href=\"#\">about 12 hours ago</a></span> <span class=\"tweet_text\">Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus <a href=\"#\">domain.com</a></span></li>\r\n");
      out.write("              <li class=\"tweet_even\"><span class=\"tweet_time\"><a href=\"#\">about a day ago</a></span> <span class=\"tweet_text\">Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus <a href=\"#\">domain.com</a></span></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"fourth-col\">\r\n");
      out.write("        <div class=\"widget-block\">\r\n");
      out.write("          <h4>CATEGORIES</h4>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">Design</a></li>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">Photo</a></li>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">Art</a></li>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">Game</a></li>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">Film</a></li>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">TV</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <!-- ENDS widgets -->\r\n");
      out.write("    <div id=\"footer-bottom\">&copy; Copyright 2012 <a href=\"#\">Company Name</a> All Rights Reserved | Website Template By <a target=\"_blank\" href=\"http://www.luiszuno.com\">luiszuno</a> | Download more: <a href=\"http://www.csstemplatesfree.org\">Free CSS Templates</a></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- ENDS wrapper -->");
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- JavaScript at the bottom for fast page loading -->\r\n");
      out.write("\t<script src=\"js/jquery-1.7.1.min.js\"></script>\r\n");
      out.write("\t<!-- scripts concatenated and minified via build script -->\r\n");
      out.write("\t<script src=\"js/custom.js\"></script>\r\n");
      out.write("\t<!-- superfish -->\r\n");
      out.write("\t<script src=\"js/superfish-1.4.8/js/hoverIntent.js\"></script>\r\n");
      out.write("\t<script src=\"js/superfish-1.4.8/js/superfish.js\"></script>\r\n");
      out.write("\t<script src=\"js/superfish-1.4.8/js/supersubs.js\"></script>\r\n");
      out.write("\t<!-- ENDS superfish -->\r\n");
      out.write("\t<script src=\"js/jquery.isotope.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.nivo.slider.js\"></script>\r\n");
      out.write("\t<script src=\"js/css3-mediaqueries.js\"></script>\r\n");
      out.write("\t<script src=\"js/tabs.js\"></script>\r\n");
      out.write("\t<script src=\"js/poshytip-1.1/src/jquery.poshytip.min.js\"></script>\r\n");
      out.write("\t<!-- end scripts -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
