/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-03-20 06:34:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/E:/semiproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/eojintemplate/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1489978280000L));
    _jspx_dependants.put("/footer.jspf", Long.valueOf(1489980826000L));
    _jspx_dependants.put("jar:file:/E:/semiproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/eojintemplate/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/header.jspf", Long.valueOf(1489991668000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<!--[if lt IE 7]> <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>    <html class=\"no-js lt-ie9 lt-ie8\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>    <html class=\"no-js lt-ie9\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("<head>\r\n");
      out.write("<title>Vintage | Contact</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/superfish.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/nivo-slider.css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/tweet.css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/lessframework.css\" media=\"all\">\r\n");
      out.write("<script src=\"js/modernizr-2.5.3.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- HEADER -->\r\n");
      out.write("<header>\r\n");
      out.write("\t");
      out.write("  <!-- header wrapper -->\r\n");
      out.write("  <div></div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"wrapper cf\">\r\n");
      out.write("    <div id=\"logo\"> <a href=\"index.jsp\" ><img src=\"img/kostalogo.png\" alt=\"\"></a> </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- ENDS header wrapper -->\r\n");
      out.write("  <!-- nav -->\r\n");
      out.write("  <nav class=\"cf\">\r\n");
      out.write("    <div class=\"wrapper cf\">\r\n");
      out.write("      <ul id=\"nav\" class=\"sf-menu\">\r\n");
      out.write("        <li><a href=\"index.jsp\">HOME<i><b></b></i></a></li>\r\n");
      out.write("        <li><a href=\"best.jsp\">Best<i><b></b></i></a>\r\n");
      out.write("<!--           <ul>\r\n");
      out.write("            <li><a href=\"page.jsp\">Columns</a></li>\r\n");
      out.write("            <li><a href=\"page-typography.jsp\">Typography</a></li>\r\n");
      out.write("            <li><a href=\"page-elements.jsp\">Elements</a></li>\r\n");
      out.write("          </ul> -->\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a href=\"bestChallenge.jsp\">Best Challenge<i><b></b></i></a></li>\r\n");
      out.write("        <li><a href=\"challenge.jsp\">Challenge<i><b></b></i></a></li>\r\n");
      out.write("        <!-- ë¡ê·¸ì¸ ìëì´ììëë  <li><a href=\"login.jsp\">member<i><b></b></i></a></li> <li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("            <li><a href=\"join.jsp\">Join</a></li>\r\n");
      out.write("            \r\n");
      out.write("\t\t            ë¡ê·¸ì¸ ëì´ììë íìì´ë©´ íìì ë³´ / ê´ë¦¬ìë©´ ê´ë¦¬ìê´ë¦¬ê° íìëê² í´ì£¼ë©´ ì¢ìë¯\r\n");
      out.write("            -->\r\n");
      out.write("\t\t        <li><a href=\"member.jsp\">member<i><b></b></i></a>\r\n");
      out.write("   \t    \t\t\t<ul>\r\n");
      out.write("       \t \t\t\t\t<li><a href=\"page-typography.jsp\">login</a></li>\r\n");
      out.write("        \t\t\t   \t<li><a href=\"page-elements.jsp\">Join</a></li>\r\n");
      out.write("       \t\t\t \t</ul>\r\n");
      out.write("        \t\t</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <div id=\"combo-holder\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- ends nav -->");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<!-- ENDS HEADER -->\r\n");
      out.write("<!-- MAIN -->\r\n");
      out.write("<div role=\"main\" id=\"main\">\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("    <!-- page-content -->\r\n");
      out.write("    <div class=\"page-content\">\r\n");
      out.write("      <!-- GOOGLE MAPS -->\r\n");
      out.write("      <script src=\"https://maps.google.com/maps/api/js?sensor=true\"></script>\r\n");
      out.write("      <script>\r\n");
      out.write("      function initialize() {\r\n");
      out.write("          var latlng = new google.maps.LatLng(-34.397, 150.644);\r\n");
      out.write("          var myOptions = {\r\n");
      out.write("              zoom: 8,\r\n");
      out.write("              center: latlng,\r\n");
      out.write("              mapTypeId: google.maps.MapTypeId.ROADMAP\r\n");
      out.write("          };\r\n");
      out.write("          var map = new google.maps.Map(document.getElementById(\"map_canvas\"),\r\n");
      out.write("          myOptions);\r\n");
      out.write("      }\r\n");
      out.write("      </script>\r\n");
      out.write("      <h2 class=\"heading\">Location</h2>\r\n");
      out.write("      <div id=\"map_canvas\"></div>\r\n");
      out.write("      <p> Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet.</p>\r\n");
      out.write("      <!-- ENDS GOOGLE MAPS -->\r\n");
      out.write("      <h2 class=\"heading\">Contact Form</h2>\r\n");
      out.write("      <!-- form -->\r\n");
      out.write("      <form id=\"contactForm\" action=\"#\" method=\"post\">\r\n");
      out.write("        <fieldset>\r\n");
      out.write("          <p>\r\n");
      out.write("            <label for=\"name\" >Name</label>\r\n");
      out.write("            <input name=\"name\"  id=\"name\" type=\"text\" class=\"form-poshytip\" title=\"Enter your full name\">\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <label for=\"email\" >Email</label>\r\n");
      out.write("            <input name=\"email\"  id=\"email\" type=\"text\" class=\"form-poshytip\" title=\"Enter your email address\">\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <label for=\"web\">Website</label>\r\n");
      out.write("            <input name=\"web\"  id=\"web\" type=\"text\" class=\"form-poshytip\" title=\"Enter your website\">\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <label for=\"comments\">Message</label>\r\n");
      out.write("            <textarea  name=\"comments\"  id=\"comments\" rows=\"5\" cols=\"20\" class=\"form-poshytip\" title=\"Enter your comments\"></textarea>\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <input type=\"button\" value=\"Send\" name=\"submit\" id=\"submit\">\r\n");
      out.write("            <span id=\"error\" class=\"warning\">Error Message</span></p>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("      </form>\r\n");
      out.write("      <p id=\"sent-form-msg\" class=\"success\">Form data sent. Thanks for your comments.</p>\r\n");
      out.write("      <!-- ENDS form -->\r\n");
      out.write("      <div class=\"c-1\"></div>\r\n");
      out.write("      <div class=\"c-2\"></div>\r\n");
      out.write("      <div class=\"c-3\"></div>\r\n");
      out.write("      <div class=\"c-4\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ENDS page-content -->\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ENDS MAIN -->\r\n");
      out.write("<footer>\r\n");
      out.write("\t");
      out.write("  <!-- wrapper -->\r\n");
      out.write("  <div class=\"wrapper cf\">\r\n");
      out.write("    <!-- social -->\r\n");
      out.write("    <div class=\"sb-holder cf\">\r\n");
      out.write("      <ul id=\"social-bar\" class=\"cf\">\r\n");
      out.write("        <li class=\"left-corner\"><i></i></li>\r\n");
      out.write("        <li><a href=\"#\" title=\"Become a fan\"><img src=\"img/social/Facebook.png\" alt=\"\"></a></li>\r\n");
      out.write("        <li><a href=\"#\" title=\"Follow my tweets\"><img src=\"img/social/Twitter.png\" alt=\"\"></a></li>\r\n");
      out.write("        <li><a href=\"#\" title=\"Add to the circle\"><img src=\"img/social/Google+.png\" alt=\"\"></a></li>\r\n");
      out.write("        <li class=\"right-corner\"><i></i></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ENDS social -->\r\n");
      out.write("    <!-- widgets -->\r\n");
      out.write("    <ul  class=\"widget-cols cf\">\r\n");
      out.write("      <li class=\"first-col\">\r\n");
      out.write("        <div class=\"widget-block\">\r\n");
      out.write("          <h4>RECENT POSTS</h4>\r\n");
      out.write("          <div class=\"recent-post cf\"> <a href=\"#\" class=\"thumb\"><img src=\"img/dummies/54x54.gif\" alt=\"\"></a>\r\n");
      out.write("            <div class=\"post-head\"> <a href=\"#\">Pellentesque habitant morbi senectus </a><span> March 12, 2011</span> </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"recent-post cf\"> <a href=\"#\" class=\"thumb\"><img src=\"img/dummies/54x54b.gif\" alt=\"\"></a>\r\n");
      out.write("            <div class=\"post-head\"> <a href=\"#\">Pellentesque habitant morbi senectus</a><span> March 12, 2011</span> </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"recent-post cf\"> <a href=\"#\" class=\"thumb\"><img src=\"img/dummies/54x54c.gif\" alt=\"\"></a>\r\n");
      out.write("            <div class=\"post-head\"> <a href=\"#\">Pellentesque habitant morbi senectus</a><span> March 12, 2011</span> </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"second-col\">\r\n");
      out.write("        <div class=\"widget-block\">\r\n");
      out.write("          <h4>ABOUT</h4>\r\n");
      out.write("          <p>Vintage Template it's completely free this means you don't have to pay anything.</p>\r\n");
      out.write("          <p>Placeholder images by twistedfork.me</p>\r\n");
      out.write("          <p>Visit our site and find the most beautiful free templates up to date.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"third-col\">\r\n");
      out.write("        <div class=\"widget-block\">\r\n");
      out.write("          <div id=\"tweets\" class=\"footer-col tweet\">\r\n");
      out.write("            <h4>TWITTER WIDGET</h4>\r\n");
      out.write("            <ul class=\"tweet_list\">\r\n");
      out.write("              <li class=\"tweet_first tweet_odd\"><span class=\"tweet_time\"><a href=\"#\">about 12 hours ago</a></span> <span class=\"tweet_text\">Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus <a href=\"#\">domain.com</a></span></li>\r\n");
      out.write("              <li class=\"tweet_even\"><span class=\"tweet_time\"><a href=\"#\">about a day ago</a></span> <span class=\"tweet_text\">Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus <a href=\"#\">domain.com</a></span></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"fourth-col\">\r\n");
      out.write("        <div class=\"widget-block\">\r\n");
      out.write("          <h4>CATEGORIES</h4>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">Design</a></li>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">Photo</a></li>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">Art</a></li>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">Game</a></li>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">Film</a></li>\r\n");
      out.write("            <li class=\"cat-item\"><a href=\"#\">TV</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <!-- ENDS widgets -->\r\n");
      out.write("    <div id=\"footer-bottom\">&copy; Copyright 2012 <a href=\"#\">Company Name</a> All Rights Reserved | Website Template By <a target=\"_blank\" href=\"http://www.luiszuno.com\">luiszuno</a> | Download more: <a href=\"http://www.csstemplatesfree.org\">Free CSS Templates</a></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- ENDS wrapper -->");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- JavaScript at the bottom for fast page loading -->\r\n");
      out.write("<script src=\"js/jquery-1.7.1.min.js\"></script>\r\n");
      out.write("<!-- scripts concatenated and minified via build script -->\r\n");
      out.write("<script src=\"js/custom.js\"></script>\r\n");
      out.write("<!-- superfish -->\r\n");
      out.write("<script src=\"js/superfish-1.4.8/js/hoverIntent.js\"></script>\r\n");
      out.write("<script src=\"js/superfish-1.4.8/js/superfish.js\"></script>\r\n");
      out.write("<script src=\"js/superfish-1.4.8/js/supersubs.js\"></script>\r\n");
      out.write("<!-- ENDS superfish -->\r\n");
      out.write("<script src=\"js/jquery.isotope.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.nivo.slider.js\"></script>\r\n");
      out.write("<script src=\"js/css3-mediaqueries.js\"></script>\r\n");
      out.write("<script src=\"js/tabs.js\"></script>\r\n");
      out.write("<script src=\"js/poshytip-1.1/src/jquery.poshytip.min.js\"></script>\r\n");
      out.write("<!-- end scripts -->\r\n");
      out.write("<!-- Start google map -->\r\n");
      out.write("<script>initialize();</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
