/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-03-20 03:13:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_002d3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1489978280000L));
    _jspx_dependants.put("jar:file:/E:/semiproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/template/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/header.jspf", Long.valueOf(1489979530000L));
    _jspx_dependants.put("jar:file:/E:/semiproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/template/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<title>Blog</title>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name = \"format-detection\" content = \"telephone=no\" />\r\n");
      out.write("\t<link rel=\"icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/grid.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/touchTouch.css\">\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\t<script src=\"js/touchTouch.jquery.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery-migrate-1.2.1.js\"></script>\r\n");
      out.write("\t<script src=\"js/script.js\"></script>\r\n");
      out.write("\t<!--[if (gt IE 9)|!(IE)]><!-->\r\n");
      out.write("\t<script src=\"js/jquery.mobile.customized.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/wow.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function () {\r\n");
      out.write("\t\t\tif ($('html').hasClass('desktop')) {\r\n");
      out.write("\t\t\t\tnew WOW().init();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--<![endif]-->\r\n");
      out.write("\t<!--[if lt IE 8]>\r\n");
      out.write("\t<div style=' clear: both; text-align:center; position: relative;'>\r\n");
      out.write("\t <a href=\"http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode\">\r\n");
      out.write("\t\t <img src=\"images/ie8-panel/warning_bar_0000_us.jpg\" border=\"0\" height=\"42\" width=\"820\" alt=\"You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today.\" />\r\n");
      out.write("\t </a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/ie.css\">\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t<!--[if IE]>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/ie-8.css\">\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t</head>\r\n");
      out.write("<body class=\"index-3\">\r\n");
      out.write("<!--==============================header=================================-->\r\n");
      out.write("<header id=\"header\">\r\n");
      out.write("\t");
      out.write("<div id=\"stuck_container\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_12\">\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("\t\t\t\t\t<!--<div class=\"social\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><span class=\"bd-ra fa fa-facebook\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><span class=\"bd-ra fa fa-tumblr\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><span class=\"bd-ra fa fa-google-plus\"></span></a>\r\n");
      out.write("\t\t\t\t\t</div>-->\r\n");
      out.write("\t\t\t\t\t<h1><a href=\"index.jsp\">Super Star Kosta<span>who is best?</span></a></h1>\r\n");
      out.write("\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sf-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--<li class=\"current\"><a href=\"index.html\">Home</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>-->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index-1.jsp\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index-2.jsp\">Portfolio</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index-3.jsp\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index-4.jsp\">Contacts</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!--=======content================================-->\r\n");
      out.write("\r\n");
      out.write("<section id=\"content\">\r\n");
      out.write("\t<div class=\"full-width-container block-1\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_12\">\r\n");
      out.write("\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t<h2>Blog</h2>\r\n");
      out.write("\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_7\">\r\n");
      out.write("\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t<h4><a href=\"#\">Hivamus at magna non nuncerto limonit </a></h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img_block\"><img src=\"images/index-3_img-1.jpg\" alt></div>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"first\">Rehoncus. Aliquam nibh antegestas id ictum ado. Praesenterto faucibus maleada faucibusnec laeetert metus id laoreet. </p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"second\">Nullam consectetur orci sed nulla facilisisequaterto. Curabitur vel lorem sit amet nulla perermentum. Aliquam nibh ante, egestas id dictum a, commodo luctus libero. Raesent faucibus malesuada faucibus. Donecertolin laoreet metus id laoreet malesuadarem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur orci sed nulla facilisis consequat. </p>\r\n");
      out.write("\t\t\t\t\t\t<footer>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"attributes\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"line-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-calendar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">June 10, 2014</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-user\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">Admin</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-chain\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">Permalink</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"line-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-bookmark\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">Uncategorized</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-tag\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">No tags</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"line-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-comments\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">No comments</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"el-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-eye\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">182</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"el-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-thumbs-up\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">0</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"el-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-thumbs-down\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">0</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</footer>\r\n");
      out.write("\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t<h4><a href=\"#\">Givamus at magna non nuncerto limonit </a></h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img_block\"><img src=\"images/index-3_img-2.jpg\" alt></div>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"first\">Johoncus. Aliquam nibh antegestas id ictum ado. Praesenterto faucibus maleada faucibusnec laeetert metus id laoreet wer.</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"second\">Ollam consectetur orci sed nulla facilisisequaterto. Curabitur vel lorem sit amet nulla perermentum. Aliquam nibh ante, egestas id dictum a, commodo luctus libero. Raesent faucibus malesuada faucibus. Donecertolin laoreet metus id laoreet malesuadarem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur orci sed nulla facilisis consequat. </p>\r\n");
      out.write("\t\t\t\t\t\t<footer>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"attributes\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"line-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-calendar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">June 10, 2014</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-user\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">Admin</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-chain\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">Permalink</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"line-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-bookmark\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">Uncategorized</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-tag\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">No tags</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"line-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-comments\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">No comments</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"el-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-eye\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">182</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"el-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-thumbs-up\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">0</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"el-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-thumbs-down\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">0</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</footer>\r\n");
      out.write("\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t<h4><a href=\"#\">At magna non nuncerto limonit</a></h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img_block\"><img src=\"images/index-3_img-3.jpg\" alt></div>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"first\">Aliquam nibh antegestas id ictum ado. Praesenterto faucibus maleada faucibusnec laeetert metus id laoreet </p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"second\">Nullam consectetur orci sed nulla facilisisequaterto. Curabitur vel lorem sit amet nulla perermentum. Aliquam nibh ante, egestas id dictum a, commodo luctus libero. Raesent faucibus malesuada faucibus. Donecertolin laoreet metus id laoreet malesuadarem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur orci sed nulla facilisis consequater. </p>\r\n");
      out.write("\t\t\t\t\t\t<footer>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"attributes\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"line-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-calendar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">June 10, 2014</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-user\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">Admin</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-chain\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">Permalink</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"line-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-bookmark\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">Uncategorized</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-tag\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">No tags</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"line-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-comments\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">No comments</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"attr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"el-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"fa fa-eye\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\"><a href=\"#\">182</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"el-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-thumbs-up\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">0</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"el-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><span class=\"fa fa-thumbs-down\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">0</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</footer>\r\n");
      out.write("\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"grid_4 preffix_1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"item-1\">\r\n");
      out.write("\t\t\t\t\t\t<h4><a href=\"#\">Categories</a></h4>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Herem ipsum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Dolor sit</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Komet,tetur</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Odipiscingt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">In mollis eratttis</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Neque Loacilisis</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Amet ultret</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"item-2\">\r\n");
      out.write("\t\t\t\t\t\t<h4><a href=\"#\">Recent Posts</a></h4>\r\n");
      out.write("\t\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"img_block\"><img src=\"images/index-3_img-4.jpg\" alt=\"news\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"time\"><a href=\"#\">20-05-2014</a></h5>\r\n");
      out.write("\t\t\t\t\t\t\t<h5><a href=\"#\">Hivamus at magnate </a></h5>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Rehoncus. Aliquam nibh tegestas id ictum ado. Praesentertoaucibus maleada </p>\r\n");
      out.write("\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"img_block\"><img src=\"images/index-3_img-5.jpg\" alt=\"news\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"time\"><a href=\"#\">27-05-2014</a></h5>\r\n");
      out.write("\t\t\t\t\t\t\t<h5><a href=\"#\">Livamus aot magte</a></h5>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Tehoncus. Aliquam nibh tegestas id ictum ado. Praesentertoaucibus maleada</p>\r\n");
      out.write("\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"img_block\"><img src=\"images/index-3_img-6.jpg\" alt=\"news\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"time\"><a href=\"#\">29-05-2014</a></h5>\r\n");
      out.write("\t\t\t\t\t\t\t<h5><a href=\"#\">Kivamus aagnateme </a></h5>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Mehoncusiquam nibh tegestas id ictum ado. Praesentertoaucibus maleada </p>\r\n");
      out.write("\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!--=======footer=================================-->\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t<pre>© <span id=\"copyright-year\"></span> |  Privacy Policy</pre>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer_bottom\"><a href=\"http://www.templatemonster.com/\" rel=\"nofollow\"><img src=\"images/footer-logo.png\" alt=\"logo\"></a></div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
