/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-03-20 03:17:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_002d4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1489978280000L));
    _jspx_dependants.put("jar:file:/E:/semiproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/template/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/header.jspf", Long.valueOf(1489979530000L));
    _jspx_dependants.put("jar:file:/E:/semiproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/template/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<title>Contacts</title>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name = \"format-detection\" content = \"telephone=no\" />\r\n");
      out.write("\t<link rel=\"icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/grid.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/contact-form.css\">\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery-migrate-1.2.1.js\"></script>\r\n");
      out.write("\t<script src=\"js/script.js\"></script>\r\n");
      out.write("\t<script src=\"js/TMForm.js\"></script>\r\n");
      out.write("\t<script src=\"js/modal.js\"></script>\r\n");
      out.write("\t<script src='//maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false'></script>\r\n");
      out.write("\t<!--[if (gt IE 9)|!(IE)]><!-->\r\n");
      out.write("\t<script src=\"js/jquery.mobile.customized.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/wow.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function () {\r\n");
      out.write("\t\t\tif ($('html').hasClass('desktop')) {\r\n");
      out.write("\t\t\t\tnew WOW().init();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--<![endif]-->\r\n");
      out.write("\t<!--[if lt IE 8]>\r\n");
      out.write("\t<div style=' clear: both; text-align:center; position: relative;'>\r\n");
      out.write("\t <a href=\"http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode\">\r\n");
      out.write("\t\t <img src=\"images/ie8-panel/warning_bar_0000_us.jpg\" border=\"0\" height=\"42\" width=\"820\" alt=\"You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today.\" />\r\n");
      out.write("\t </a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/ie.css\">\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t<!--[if IE]>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/ie-8.css\">\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t</head>\r\n");
      out.write("<body class=\"index-4\">\r\n");
      out.write("<!--==============================header=================================-->\r\n");
      out.write("<header id=\"header\">\r\n");
      out.write("\t");
      out.write("<div id=\"stuck_container\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_12\">\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("\t\t\t\t\t<!--<div class=\"social\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><span class=\"bd-ra fa fa-facebook\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><span class=\"bd-ra fa fa-tumblr\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><span class=\"bd-ra fa fa-google-plus\"></span></a>\r\n");
      out.write("\t\t\t\t\t</div>-->\r\n");
      out.write("\t\t\t\t\t<h1><a href=\"index.jsp\">Super Star Kosta<span>who is best?</span></a></h1>\r\n");
      out.write("\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sf-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--<li class=\"current\"><a href=\"index.html\">Home</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>-->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index-1.jsp\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index-2.jsp\">Portfolio</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index-3.jsp\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index-4.jsp\">Contacts</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!--=======content================================-->\r\n");
      out.write("\r\n");
      out.write("<section id=\"content\">\r\n");
      out.write("\t<div class=\"full-width-container block-1\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_12\">\r\n");
      out.write("\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t<h2><span>Our Locations</span></h2>\r\n");
      out.write("\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t<div class=\"content_map\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"google-map-api\"> \r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"map-canvas\" class=\"gmap\"></div> \r\n");
      out.write("\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"full-width-container block-2\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_5\">\r\n");
      out.write("\t\t\t\t\t<form id=\"contact-form\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"contact-form-loader\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2><span>Contact Form</span></h2>\r\n");
      out.write("\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"text\">Your Name:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" placeholder=\"\" value=\"\" data-constraints=\"@Required @JustLetters\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"empty-message\">*This field is required.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"error-message\">*This is not a valid name.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"text\">Your E-mail:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\" placeholder=\"\" value=\"\" data-constraints=\"@Required @Email\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"empty-message\">*This field is required.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"error-message\">*This is not a valid email.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"phone\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"text\">Subject:</span>\r\n");
      out.write("\t\t\t\t\t\t\t              <input type=\"text\" name=\"state\" placeholder=\"\" data-constraints=\"@JustLetters\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"message\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"text\">Message:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea name=\"message\" placeholder=\"\" data-constraints='@Required @Length(min=20,max=999999)'></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"empty-message\">*This field is required.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"error-message\">*The message is too short.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cont_btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" data-type=\"reset\" class=\"btn\">clear</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" data-type=\"submit\" class=\"btn\">send</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</fieldset> \r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal fade response-message\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"modal-title\">Modal title</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tYou message has been sent! We will be in touch soon.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"grid_6 preffix_1\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t<h2><span>Contact Information</span></h2>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"el-1\">\r\n");
      out.write("\t\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur orci sed Curabitur vel lorem sit amet nulla ullamcorper fermentum. In vitae varius augue, eu consectetur ligula. Etiam dui eros, laoreet sit amet est vel\r\n");
      out.write("\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur orci sed Curabitur vel lorem sit amet nulla ullamcorper fermentum. In vitae varius augue, eu consectetur ligula. Etiam dui eros, laoreet sit amet est vel, commodo venenatis eros.Lamus at magna non nunc tristique rhoncuseri tym.\r\n");
      out.write("\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\tEtiam dui eros, laoreet sit amet est vel, commodo venenatis eros.Lamus at magna non nunc tristique rhoncuseri tym. Etiam dui eros, laoreet sit amet est vel, commodo venenatis eros.Lamus at magna non nunc tristique.honcuseri tym. Etiam dui eros, laoreet sit amet est vel, commodo venenatis eromus at magna <br><br><br>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"grid_3 alpha\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"address\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>The Company Name Inc. <br>9870 St Vincent Place, <br>Glasgow, DC 45 Fr 45.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"grid_3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"address\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>Telephone:+1 800 603 6035 <br>FAX:+1 800 889 9898 <br>E-mail: <a href=\"mailto:mail@demolink.org\" class=\"mail\">mail@demolink.org</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!--=======footer=================================-->\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t<pre>© <span id=\"copyright-year\"></span> |  Privacy Policy</pre>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer_bottom\"><a href=\"http://www.templatemonster.com/\" rel=\"nofollow\"><img src=\"images/footer-logo.png\" alt=\"logo\"></a></div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tgoogle_api_map_init();\r\n");
      out.write("\t\tfunction google_api_map_init(){\r\n");
      out.write("\t\t\tvar map;\r\n");
      out.write("\t\t\tvar coordData = new google.maps.LatLng(parseFloat(40.6894388), parseFloat(-73.9036233,10)); \r\n");
      out.write("\r\n");
      out.write("\t\t\tvar styleArray = [\r\n");
      out.write("\t\t\t\t{\"featureType\":\"water\",\"stylers\":[{\"color\":\"#021019\"}]},\r\n");
      out.write("\t\t\t\t{\"featureType\":\"landscape\",\"stylers\":[{\"color\":\"#08304b\"}]},\r\n");
      out.write("\t\t\t\t{\"featureType\":\"poi\",\"elementType\":\"geometry\",\"stylers\":[{\"color\":\"#0c4152\"},{\"lightness\":5}]},\r\n");
      out.write("\t\t\t\t{\"featureType\":\"road.highway\",\"elementType\":\"geometry.fill\",\"stylers\":[{\"color\":\"#000000\"}]},\r\n");
      out.write("\t\t\t\t{\"featureType\":\"road.highway\",\"elementType\":\"geometry.stroke\",\"stylers\":[{\"color\":\"#0b434f\"},{\"lightness\":25}]},\r\n");
      out.write("\t\t\t\t{\"featureType\":\"road.arterial\",\"elementType\":\"geometry.fill\",\"stylers\":[{\"color\":\"#000000\"}]},\r\n");
      out.write("\t\t\t\t{\"featureType\":\"road.arterial\",\"elementType\":\"geometry.stroke\",\"stylers\":[{\"color\":\"#0b3d51\"},{\"lightness\":16}]},\r\n");
      out.write("\t\t\t\t{\"featureType\":\"road.local\",\"elementType\":\"geometry\",\"stylers\":[{\"color\":\"#000000\"}]},\r\n");
      out.write("\t\t\t\t{\"elementType\":\"labels.text.fill\",\"stylers\":[{\"color\":\"#ffffff\"}]},\r\n");
      out.write("\t\t\t\t{\"elementType\":\"labels.text.stroke\",\"stylers\":[{\"color\":\"#000000\"},{\"lightness\":13}]},\r\n");
      out.write("\t\t\t\t{\"featureType\":\"transit\",\"stylers\":[{\"color\":\"#146474\"}]},\r\n");
      out.write("\t\t\t\t{\"featureType\":\"administrative\",\"elementType\":\"geometry.fill\",\"stylers\":[{\"color\":\"#000000\"}]},\r\n");
      out.write("\t\t\t\t{\"featureType\":\"administrative\",\"elementType\":\"geometry.stroke\",\"stylers\":[{\"color\":\"#144b53\"},{\"lightness\":14},{\"weight\":1.4}]}\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\tfunction initialize() { \r\n");
      out.write("\t\t\t  var mapOptions = { \r\n");
      out.write("\t\t\t\tzoom: 12, \r\n");
      out.write("\t\t\t\tcenter: coordData, \r\n");
      out.write("\t\t\t\tscrollwheel: false, \r\n");
      out.write("\t\t\t\tstyles: styleArray \r\n");
      out.write("\t\t\t  } \r\n");
      out.write(" \r\n");
      out.write("\t\t\t  var contentString = \"<div></div>\"; \r\n");
      out.write("\t\t\t  var infowindow = new google.maps.InfoWindow({ \r\n");
      out.write("\t\t\t\tcontent: contentString, \r\n");
      out.write("\t\t\t\tmaxWidth: 200 \r\n");
      out.write("\t\t\t  }); \r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t  var map = new google.maps.Map(document.getElementById(\"map-canvas\"), mapOptions); \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tgoogle.maps.event.addDomListener(window, 'resize', function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t  map.setCenter(coordData);\r\n");
      out.write("\r\n");
      out.write("\t\t\t  var center = map.getCenter();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tgoogle.maps.event.addDomListener(window, \"load\", initialize); \r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- coded by Fred -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
